add_files \
E:\work\AXI\interface_define\axi_inf.sv \
E:\work\AXI\interface_define\axi_lite_inf.sv \
E:\work\AXI\interface_define\axi_stream_inf.sv \
E:\work\AXI\platform_ip\fifo_36bit_A1.sv \
E:\work\AXI\platform_ip\fifo_36bit.sv \
E:\work\AXI\platform_ip\fifo_37_72bit.sv \
E:\work\AXI\platform_ip\fifo_73_96bit.sv \
E:\work\AXI\platform_ip\fifo_97_144bit_A1.sv \
E:\work\AXI\platform_ip\fifo_97_144bit.sv \
E:\work\AXI\platform_ip\fifo_ku_18bit.sv \
E:\work\AXI\platform_ip\fifo_ku_36bit.sv \
E:\work\AXI\platform_ip\fifo_ku.sv \
E:\work\AXI\platform_ip\ku_long_fifo_4bit.sv \
E:\work\AXI\platform_ip\long_fifo_4bit_8192.sv \
E:\work\AXI\platform_ip\long_fifo_4bit_SL8192.sv \
E:\work\AXI\platform_ip\long_fifo_4bit.sv \
E:\work\AXI\platform_ip\long_fifo_verb.sv \
E:\work\AXI\platform_ip\long_fifo.sv \
E:\work\AXI\platform_ip\xilinx_fifo_A1.sv \
E:\work\AXI\platform_ip\xilinx_fifo_verb.sv \
E:\work\repository\xilinx_clock_reset\xilinx_reset_sync.v \
E:\work\AXI\common_fifo\common_fifo.sv \
E:\work\AXI\common_fifo\independent_clock_fifo.sv \
