add_files \
E:/work/AXI/AXI4/axi4_direct.sv \
E:/work/AXI/AXI4/axi4_long_to_axi4_wide.sv \
E:/work/AXI/AXI4/axi4_rd_auxiliary_batch_gen.sv \
E:/work/AXI/AXI4/axi4_rd_auxiliary_gen_A1.sv \
E:/work/AXI/AXI4/axi4_wr_auxiliary_batch_gen.sv \
E:/work/AXI/AXI4/axi4_wr_auxiliary_gen_without_resp.sv \
E:/work/AXI/AXI4/axi4_wr_auxiliary_gen.sv \
E:/work/AXI/AXI4/axi4_rd_burst_track.sv \
E:/work/AXI/AXI4/axi4_wr_burst_track.sv \
E:/work/AXI/AXI4/axi4_long_to_axi4_wide.sv \
E:/work/AXI/AXI4/axi4_long_to_axi4_wide_A1.sv \
E:/work/AXI/AXI4/interconnect/axi4_mix_interconnect_M2S.sv \
E:/work/AXI/AXI4/interconnect/axi4_wr_interconnect_M2S_A1.sv \
E:/work/AXI/AXI4/interconnect/axi4_rd_mix_interconnect_M2S_A1.sv \
E:/work/AXI/AXI4/packet_fifo/axi4_packet_fifo.sv \
E:/work/AXI/AXI4/packet_fifo/axi4_rd_packet_fifo.sv \
E:/work/AXI/AXI4/packet_fifo/axi4_wr_packet_fifo.sv \
E:/work/AXI/AXI4/packet_partition/axi4_partition_OD.sv \
E:/work/AXI/AXI4/packet_partition/axi4_partition_rd_OD.sv \
E:/work/AXI/AXI4/packet_partition/axi4_partition_wr_OD.sv \
E:/work/AXI/AXI4/width_convert/width_convert_verb.sv \
E:/work/AXI/AXI4/width_convert/width_combin.sv \
E:/work/AXI/AXI4/width_convert/width_convert.sv \
E:/work/AXI/AXI4/width_convert/width_destruct.sv \
E:/work/AXI/AXI4/width_convert/odd_width_convert.sv \
E:/work/AXI/AXI4/width_convert/simple_data_pipe_slaver.sv \
E:/work/AXI/AXI4/width_convert/simple_data_pipe.sv
