add_files \
E:/work/AXI/AXI_stream/packet_fifo/axi_stream_long_fifo.sv \
E:/work/AXI/AXI_stream/packet_fifo/axi_stream_packet_fifo.sv \
E:/work/AXI/AXI_stream/axi_stream_interconnect_M2S_noaddr.sv \
E:/work/AXI/AXI_stream/axi_stream_interconnect_M2S.sv \
E:/work/AXI/AXI_stream/axi_stream_interconnect_S2M.sv \
E:/work/AXI/AXI_stream/axi_stream_partition.sv \
E:/work/AXI/AXI_stream/axi_streams_combin.sv \
E:/work/AXI/AXI_stream/axi_streams_scaler.sv \
E:/work/AXI/AXI_stream/axis_append_A1.sv \
E:/work/AXI/AXI_stream/axis_append.sv \
E:/work/AXI/AXI_stream/axis_connect_pipe.sv \
E:/work/AXI/AXI_stream/axis_direct.sv \
E:/work/AXI/AXI_stream/axis_interconnect_S2M_pipe.sv \
E:/work/AXI/AXI_stream/axis_slaver_empty.sv \
E:/work/AXI/AXI_stream/axis_to_data_inf.sv \
E:/work/AXI/AXI_stream/axis_valve.sv \
E:/work/AXI/AXI_stream/data_to_axis_inf.sv \
E:/work/AXI/AXI_stream/data_to_axis_inf_A1.sv \
E:/work/AXI/AXI_stream/gen_big_field_table.sv \
E:/work/AXI/AXI_stream/gen_common_frame_table.sv \
E:/work/AXI/AXI_stream/gen_origin_axis.sv \
E:/work/AXI/AXI_stream/gen_simple_axis.sv \
E:/work/AXI/AXI_stream/parse_big_field_table.sv \
E:/work/AXI/AXI_stream/parse_common_frame_table_A1.sv \
E:/work/AXI/AXI_stream/parse_common_frame_table.sv 
